package sh.komet.rules;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javafx.scene.control.MenuItem;
import org.controlsfx.control.PropertySheet;
import org.controlsfx.control.PropertySheet.Item;
import sh.isaac.api.observable.ObservableCategorizedVersion;
import sh.isaac.api.ConceptProxy;
import sh.isaac.api.Get;
import sh.isaac.api.component.concept.ConceptSpecification;
import sh.isaac.api.Status;
import sh.isaac.provider.drools.AddEditLogicalExpressionNodeMenuItems;
import sh.komet.gui.control.PropertySheetMenuItem;
import sh.komet.gui.manifold.Manifold;
import javafx.beans.property.Property;
import sh.isaac.MetaData;
import sh.isaac.api.bootstrap.TermAux;
import sh.isaac.api.chronicle.VersionCategory;
import sh.isaac.api.chronicle.VersionType;
import sh.komet.gui.control.concept.PropertySheetItemConceptWrapper;
import sh.komet.gui.control.PropertyEditorType;
import sh.komet.gui.control.property.PropertySheetItem;
import sh.komet.gui.control.property.PropertySheetPurpose;
import sh.komet.gui.control.property.EditorType;
import sh.isaac.api.logic.NodeSemantic;


rule "Setup language"
   lock-on-active true
when
   $propertySheetItem : PropertySheetItem(getSpecification().getNid() == MetaData.LANGUAGE_CONCEPT_NID_FOR_DESCRIPTION____SOLOR.getNid());
then
   $propertySheetItem.setEditorType(EditorType.CONCEPT_SPEC_CHOICE_BOX);
   $propertySheetItem.setDefaultValueIfUnknown(MetaData.ENGLISH_LANGUAGE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.ENGLISH_LANGUAGE____SOLOR);
   
   $propertySheetItem.getAllowedValues().add(MetaData.SPANISH_LANGUAGE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.FRENCH_LANGUAGE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.JAPANESE_LANGUAGE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.LITHUANIAN_LANGUAGE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.POLISH_LANGUAGE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.SWEDISH_LANGUAGE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.CHINESE_LANGUAGE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.DANISH_LANGUAGE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.DUTCH_LANGUAGE____SOLOR);
end

rule "Setup description type"
   lock-on-active true
when
   $propertySheetItem : PropertySheetItem(getSpecification().getNid() == MetaData.DESCRIPTION_TYPE_FOR_DESCRIPTION____SOLOR.getNid());
then
   $propertySheetItem.setEditorType(EditorType.CONCEPT_SPEC_CHOICE_BOX);
   $propertySheetItem.setDefaultValueIfUnknown(MetaData.FULLY_QUALIFIED_NAME_DESCRIPTION_TYPE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.FULLY_QUALIFIED_NAME_DESCRIPTION_TYPE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.REGULAR_NAME_DESCRIPTION_TYPE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.DEFINITION_DESCRIPTION_TYPE____SOLOR);
end

rule "Setup case significance"
   lock-on-active true
when
   $propertySheetItem : PropertySheetItem(getSpecification().getNid() == MetaData.CASE_SIGNIFICANCE_CONCEPT_NID_FOR_DESCRIPTION____SOLOR.getNid());
then
   $propertySheetItem.setEditorType(EditorType.CONCEPT_SPEC_CHOICE_BOX);
   $propertySheetItem.setDefaultValueIfUnknown(MetaData.DESCRIPTION_NOT_CASE_SENSITIVE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.DESCRIPTION_NOT_CASE_SENSITIVE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.DESCRIPTION_CASE_SENSITIVE____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.DESCRIPTION_INITIAL_CHARACTER_CASE_SENSITIVE____SOLOR);
end


rule "Setup status"
   lock-on-active true
when
   $propertySheetItem : PropertySheetItem(getSpecification().getNid() == MetaData.STATUS_FOR_VERSION____SOLOR.getNid());
then
   $propertySheetItem.setEditorType(EditorType.OBJECT_CHOICE_BOX);
   $propertySheetItem.setDefaultValueIfUnknown(Status.ACTIVE);
   $propertySheetItem.getAllowedValues().add(Status.ACTIVE);
   $propertySheetItem.getAllowedValues().add(Status.INACTIVE);
   $propertySheetItem.getAllowedValues().add(Status.WITHDRAWN);
end

rule "Setup text for description"
   lock-on-active true
when
   $propertySheetItem : PropertySheetItem(getSpecification().getNid() == MetaData.TEXT_FOR_DESCRIPTION____SOLOR.getNid());
then
   $propertySheetItem.setEditorType(EditorType.TEXT);
end

rule "Setup dialect assemblage"
   lock-on-active true
when
   $propertySheetItem : PropertySheetItem(getSpecification().getNid() == MetaData.ASSEMBLAGE_NID_FOR_COMPONENT____SOLOR.getNid(), 
   getPropertySheetPurpose() == PropertySheetPurpose.DESCRIPTION_DIALECT);
then
   $propertySheetItem.setEditorType(EditorType.CONCEPT_SPEC_CHOICE_BOX);
   $propertySheetItem.setDefaultValueIfUnknown(MetaData.US_ENGLISH_DIALECT____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.US_ENGLISH_DIALECT____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.US_NURSING_DIALECT____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.GB_ENGLISH_DIALECT____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.LATIN_AMERICAN_SPANISH_DIALECT_ASSEMBLAGE____SOLOR);
   $propertySheetItem.getAllowedValues().add(ConceptProxy.make("Human Dx US English dialect","64c3a9a0-85cf-4855-9b90-2061adac2112"));
end

rule "Setup dialect acceptability"
   lock-on-active true
when
   $propertySheetItem : PropertySheetItem(getSpecification().getNid() == MetaData.COMPONENT_NID_FOR_SEMANTIC____SOLOR.getNid(), 
   getPropertySheetPurpose() == PropertySheetPurpose.DESCRIPTION_DIALECT);
then
   $propertySheetItem.setEditorType(EditorType.CONCEPT_SPEC_CHOICE_BOX);
   $propertySheetItem.setDefaultValueIfUnknown(MetaData.PREFERRED____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.PREFERRED____SOLOR);
   $propertySheetItem.getAllowedValues().add(MetaData.ACCEPTABLE____SOLOR);
end

rule "Setup assemblage semantic"
   lock-on-active true
when
   $propertySheetItem : PropertySheetItem(getSpecification().getNid() == TermAux.SEMANTIC_TYPE.getNid()); 
then
   $propertySheetItem.setEditorType(EditorType.CONCEPT_SPEC_CHOICE_BOX);
   $propertySheetItem.setDefaultValueIfUnknown(TermAux.MEMBERSHIP_SEMANTIC);
   $propertySheetItem.getAllowedValues().add(TermAux.MEMBERSHIP_SEMANTIC);
   $propertySheetItem.getAllowedValues().add(TermAux.CONCEPT_SEMANTIC);
   $propertySheetItem.getAllowedValues().add(TermAux.COMPONENT_SEMANTIC);
   $propertySheetItem.getAllowedValues().add(TermAux.INTEGER_SEMANTIC);
   $propertySheetItem.getAllowedValues().add(TermAux.STRING_SEMANTIC);
end
