/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 *
 * You may not use this file except in compliance with the License.
 *
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Contributions from 2013-2017 where performed either by US government
 * employees, or under US Veterans Health Administration contracts.
 *
 * US Veterans Health Administration contributions by government employees
 * are work of the U.S. Government and are not subject to copyright
 * protection in the United States. Portions contributed by government
 * employees are USGovWork (17USC §105). Not subject to copyright.
 * 
 * Contribution by contractors to the US Veterans Health Administration
 * during this period are contractually contributed under the
 * Apache License, Version 2.0.
 *
 * See: https://www.usa.gov/government-works
 * 
 * Contributions prior to 2013:
 *
 * Copyright (C) International Health Terminology Standards Development Organisation.
 * Licensed under the Apache License, Version 2.0.
 *
 */

package sh.isaac.misc.constants;

import java.lang.reflect.Field;
import java.util.UUID;
import javax.inject.Singleton;
import org.jvnet.hk2.annotations.Service;
import sh.isaac.api.StaticIsaacCache;
import sh.isaac.api.bootstrap.TermAux;
import sh.isaac.api.component.concept.ConceptSpecification;
import sh.isaac.api.constants.MetadataConceptConstant;
import sh.isaac.api.constants.ModuleProvidedConstants;

/**
 * 
 * {@link VHATConstants}
 * 
 * A bunch of constants that actually gets generated by the VHAT DB loader.
 * It is the VHAT DB Loaders job to validate that the UUIDs match these hard-coded values.
 * 
 * If you add any additional constants here, please add sanity checkers the the ISAAC-term-convert-vhat VhatUtil class.
 *
 * @author <a href="mailto:joel.kniaz.list@gmail.com">Joel Kniaz</a>
 *
 */
@Service
@Singleton
public class VHATConstants implements ModuleProvidedConstants, StaticIsaacCache
{

	public final static MetadataConceptConstant VHAT_HAS_PARENT_ASSOCIATION_TYPE = new MetadataConceptConstant("has_parent",
			UUID.fromString("6c2913ab-70c6-5547-9055-df62e6599bfb")){};

	public final static MetadataConceptConstant VHAT_ABBREVIATION = new MetadataConceptConstant("Abbreviation",
			UUID.fromString("9e31289b-e317-5700-88b2-93f377787b05")){};

	public final static MetadataConceptConstant VHAT_FULLY_SPECIFIED_NAME = new MetadataConceptConstant("Fully Specified Name",
			UUID.fromString("82ffe8f8-e844-511c-a4af-67f766b2a42d")){};

	public final static MetadataConceptConstant VHAT_PREFERRED_NAME = new MetadataConceptConstant("Preferred Name",
			UUID.fromString("db3f8cba-e736-5f02-a58e-0a64f562e281")){};

	public final static MetadataConceptConstant VHAT_SYNONYM = 
			new MetadataConceptConstant("Synonym", UUID.fromString("2e2f63ec-afed-5256-b0c8-d8ee99df51ae")){};

	public final static MetadataConceptConstant VHAT_VISTA_NAME = new MetadataConceptConstant("VistA Name",
			UUID.fromString("7943e9ae-7049-57e4-bf73-3c34c75e8484")){};

	public final static MetadataConceptConstant VHAT_ATTRIBUTE_TYPES = new MetadataConceptConstant("VHAT Attribute Types",
			UUID.fromString("f82bf8c1-f1a0-5aef-b03e-d5f4e3566c64")){};

	public final static MetadataConceptConstant VHAT_REFSETS = new MetadataConceptConstant("VHAT Refsets",
			UUID.fromString("1fe57571-5203-5475-9741-9b5e34c4e6a2")){};

	public final static MetadataConceptConstant VHAT_ROOT_CONCEPT = 
			new MetadataConceptConstant("VHAT", UUID.fromString("a742e928-c86a-51e0-93b5-8fd72e022e34")){};

	public final static MetadataConceptConstant VHAT_DESCRIPTION_TYPES = new MetadataConceptConstant("VHAT Description Types",
			UUID.fromString("e8c6aa5f-243f-5f99-b0b5-84c046a79b7a")){};

	public final static MetadataConceptConstant VHAT_ALL_CONCEPTS = new MetadataConceptConstant("All VHAT Concepts",
			UUID.fromString("30230ef4-41ac-5b76-95be-94ed60b607e3")){};

	public final static MetadataConceptConstant VHAT_MISSING_SDO_CODE_SYSTEM_CONCEPTS = new MetadataConceptConstant("Missing SDO Code System Concepts",
			UUID.fromString("52460eeb-1388-512d-a5e4-fddd64fe0aee")){};

	public final static MetadataConceptConstant VHAT_ASSOCIATION_TYPES = new MetadataConceptConstant("VHAT Association Types",
			UUID.fromString("60bfef74-0ff2-50f3-8083-ff400a682324")){};

	@Override
	public MetadataConceptConstant[] getConstantsToCreate()
	{
		//Nothing from this class should be generated into the DB, they are made by the DB loaders.
		return new MetadataConceptConstant[] {};
	}

	@Override
	public MetadataConceptConstant[] getConstantsForInfoOnly()
	{
		return new MetadataConceptConstant[] { VHAT_HAS_PARENT_ASSOCIATION_TYPE, VHAT_ABBREVIATION, VHAT_FULLY_SPECIFIED_NAME, VHAT_PREFERRED_NAME,
				VHAT_SYNONYM, VHAT_VISTA_NAME, VHAT_ATTRIBUTE_TYPES, VHAT_REFSETS, VHAT_ROOT_CONCEPT, VHAT_DESCRIPTION_TYPES, VHAT_ALL_CONCEPTS,
				VHAT_MISSING_SDO_CODE_SYSTEM_CONCEPTS, VHAT_ASSOCIATION_TYPES };
	}

	@Override
	public void reset()
	{
		try
		{
			for (Field f : TermAux.class.getFields())
			{
				if (f.getType().equals(ConceptSpecification.class))
				{
					((ConceptSpecification) f.get(null)).clearCache();
				}
			}
		}
		catch (Exception e)
		{
			throw new RuntimeException("Unexpected error");
		}
	}
}
