/*
 * Copyright 2017 Organizations participating in ISAAC, ISAAC's KOMET, and SOLOR development include the
         US Veterans Health Administration, OSHERA, and the Health Services Platform Consortium..
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package sh.isaac.provider.drools;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javafx.scene.control.MenuItem;
import org.controlsfx.control.PropertySheet;
import org.controlsfx.control.PropertySheet.Item;
import sh.isaac.api.observable.ObservableCategorizedVersion;
import sh.isaac.api.ConceptProxy;
import sh.isaac.api.Get;
import sh.isaac.api.component.concept.ConceptSpecification;
import sh.isaac.provider.drools.AddEditVersionMenuItems;
import sh.isaac.provider.drools.PropertySheetMenuItem;
import sh.komet.gui.manifold.Manifold;
import javafx.beans.property.Property;
import sh.isaac.MetaData;
import sh.isaac.api.chronicle.VersionCategory;
import sh.isaac.api.chronicle.VersionType;
import sh.komet.gui.control.PropertySheetItemConceptWrapper;

/**
 *
 * @author kec
 */
rule "Given a AddEditVersionMenuItems, add the properties for further rule evaluation"
   lock-on-active true
when
   $addEditVersion : AddEditVersionMenuItems(getVersionType() == VersionType.CONCEPT);
then
   PropertySheetMenuItem propertySheetMenuItem = $addEditVersion.makePropertySheetMenuItem("Edit concept");
 
   Item pathProperty = $addEditVersion.getConceptProperty(MetaData.PATH_SEQUENCE_FOR_VERSION____ISAAC, "path");
   insert(propertySheetMenuItem.addItem(pathProperty));
   
   Item moduleProperty = $addEditVersion.getConceptProperty(MetaData.MODULE_SEQUENCE_FOR_VERSION____ISAAC, "module");
   insert(propertySheetMenuItem.addItem(moduleProperty));
   
   //PropertySheetItemConceptWrapper statusProperty = $addEditVersion.getProperty(MetaData.STATUS_FOR_VERSION____ISAAC);
   //insert(propertySheetMenuItem.addItem(statusProperty));
end


rule "if property specification is PATH_SEQUENCE_FOR_VERSION____ISAAC then"

when
   $property: PropertySheetItemConceptWrapper(getPropertySpecification() == MetaData.PATH_SEQUENCE_FOR_VERSION____ISAAC)
then
   $property.getAllowedValues().addAll(
      Get.assemblageService().getReferencedComponentNidStreamFromAssemblage(MetaData.PATHS_ASSEMBLAGE____ISAAC)
   );
end


rule "if property specification is STATUS_FOR_VERSION____ISAAC then"

when
   $property: PropertySheetItemConceptWrapper(getPropertySpecification() == MetaData.STATUS_FOR_VERSION____ISAAC)
then
   System.out.println("Add status capability");
end

rule "if property specification is MODULE_SEQUENCE_FOR_VERSION____ISAAC then "

when
   $property: PropertySheetItemConceptWrapper(getPropertySpecification() == MetaData.MODULE_SEQUENCE_FOR_VERSION____ISAAC)
then
   $property.getAllowedValues().add(MetaData.ISAAC_MODULE____ISAAC.getConceptSequence());
   $property.getAllowedValues().add(MetaData.SOLOR_OVERLAY_MODULE____ISAAC.getConceptSequence());
   
end
