/*
 * Copyright 2017 Organizations participating in ISAAC, ISAAC's KOMET, and SOLOR development include the
         US Veterans Health Administration, OSHERA, and the Health Services Platform Consortium..
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package sh.isaac.provider.drools;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import javafx.scene.control.MenuItem;
import org.controlsfx.control.PropertySheet;
import org.controlsfx.control.PropertySheet.Item;
import sh.isaac.api.observable.ObservableCategorizedVersion;
import sh.isaac.api.ConceptProxy;
import sh.isaac.api.Get;
import sh.isaac.api.component.concept.ConceptSpecification;
import sh.isaac.provider.drools.AddEditVersionMenuItems;
import sh.komet.gui.control.PropertySheetMenuItem;
import sh.komet.gui.manifold.Manifold;
import javafx.beans.property.Property;
import sh.isaac.MetaData;
import sh.isaac.api.chronicle.VersionCategory;
import sh.isaac.api.chronicle.VersionType;
import sh.komet.gui.control.concept.PropertySheetItemConceptWrapper;
import sh.komet.gui.control.PropertyEditorType;
/**
 *
 * @author kec
 */
 
rule "Given a AddEditVersionMenuItems, with VersionType.MEMBER, add editing options"
   lock-on-active true
when
   $addEditVersion : AddEditVersionMenuItems(getVersionType() == VersionType.MEMBER);
then
   PropertySheetMenuItem propertySheetMenuItem = $addEditVersion.makePropertySheetMenuItem("Edit attachment");
   propertySheetMenuItem.addPropertyToEdit("status", MetaData.STATUS_FOR_VERSION____SOLOR, PropertyEditorType.STATUS);
   propertySheetMenuItem.addPropertyToEdit("path", MetaData.PATH_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
   propertySheetMenuItem.addPropertyToEdit("module", MetaData.MODULE_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
end

 
rule "Given a AddEditVersionMenuItems, with VersionType.COMPONENT_NID, add editing options"
   lock-on-active true
when
   $addEditVersion : AddEditVersionMenuItems(getVersionType() == VersionType.COMPONENT_NID);
then
   PropertySheetMenuItem propertySheetMenuItem = $addEditVersion.makePropertySheetMenuItem("Edit attachment");
   propertySheetMenuItem.addPropertyToEdit("status", MetaData.STATUS_FOR_VERSION____SOLOR, PropertyEditorType.STATUS);
   propertySheetMenuItem.addPropertyToEdit("path", MetaData.PATH_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
   propertySheetMenuItem.addPropertyToEdit("module", MetaData.MODULE_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
end

rule "Given a AddEditVersionMenuItems, with VersionType.Nid1_Int2, add editing options"
   lock-on-active true
when
   $addEditVersion : AddEditVersionMenuItems(getVersionType() == VersionType.Nid1_Int2);
then
   PropertySheetMenuItem propertySheetMenuItem = $addEditVersion.makePropertySheetMenuItem("Edit attachment");
   propertySheetMenuItem.addPropertyToEdit("status", MetaData.STATUS_FOR_VERSION____SOLOR, PropertyEditorType.STATUS);
   propertySheetMenuItem.addPropertyToEdit("path", MetaData.PATH_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
   propertySheetMenuItem.addPropertyToEdit("module", MetaData.MODULE_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
   propertySheetMenuItem.addPropertyToEdit("component", MetaData.COMPONENT_ID_1____SOLOR, PropertyEditorType.CONCEPT);
   propertySheetMenuItem.addPropertyToEdit("int value", MetaData.INTEGER_2____SOLOR, PropertyEditorType.INTEGER);
end

rule "Given a AddEditVersionMenuItems, with VersionType.LONG, add editing options"
   lock-on-active true
when
   $addEditVersion : AddEditVersionMenuItems(getVersionType() == VersionType.LONG);
then
   PropertySheetMenuItem propertySheetMenuItem = $addEditVersion.makePropertySheetMenuItem("Edit attachment");
   propertySheetMenuItem.addPropertyToEdit("status", MetaData.STATUS_FOR_VERSION____SOLOR, PropertyEditorType.STATUS);
   propertySheetMenuItem.addPropertyToEdit("path", MetaData.PATH_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
   propertySheetMenuItem.addPropertyToEdit("module", MetaData.MODULE_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
end

 
rule "Given a AddEditVersionMenuItems, with VersionType.STRING, add editing options"
   lock-on-active true
when
   $addEditVersion : AddEditVersionMenuItems(getVersionType() == VersionType.STRING);
then
   PropertySheetMenuItem propertySheetMenuItem = $addEditVersion.makePropertySheetMenuItem("Edit attachment");
   propertySheetMenuItem.addPropertyToEdit("status", MetaData.STATUS_FOR_VERSION____SOLOR, PropertyEditorType.STATUS);
   propertySheetMenuItem.addPropertyToEdit("path", MetaData.PATH_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
   propertySheetMenuItem.addPropertyToEdit("module", MetaData.MODULE_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
end

 
rule "Given a AddEditVersionMenuItems, with VersionType.CONCEPT, add editing options"
   lock-on-active true
when
   $addEditVersion : AddEditVersionMenuItems(getVersionType() == VersionType.CONCEPT);
then
   PropertySheetMenuItem propertySheetMenuItem = $addEditVersion.makePropertySheetMenuItem("Edit concept");
   propertySheetMenuItem.addPropertyToEdit("status", MetaData.STATUS_FOR_VERSION____SOLOR, PropertyEditorType.STATUS);
   propertySheetMenuItem.addPropertyToEdit("path", MetaData.PATH_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
   propertySheetMenuItem.addPropertyToEdit("module", MetaData.MODULE_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
end

rule "Given a AddEditVersionMenuItems, with VersionType.DESCRIPTION, add editing options"
   lock-on-active true
when
   $addEditVersion : AddEditVersionMenuItems(getVersionType() == VersionType.DESCRIPTION);
then
   PropertySheetMenuItem propertySheetMenuItem = $addEditVersion.makePropertySheetMenuItem("Edit description");
   propertySheetMenuItem.addPropertyToEdit("text", MetaData.TEXT_FOR_DESCRIPTION____SOLOR, PropertyEditorType.TEXT);
   propertySheetMenuItem.addPropertyToEdit("type", MetaData.DESCRIPTION_TYPE_FOR_DESCRIPTION____SOLOR, PropertyEditorType.CONCEPT);
   propertySheetMenuItem.addPropertyToEdit("case significance", MetaData.CASE_SIGNIFICANCE_CONCEPT_NID_FOR_DESCRIPTION____SOLOR, PropertyEditorType.CONCEPT);
   propertySheetMenuItem.addPropertyToEdit("language", MetaData.LANGUAGE_CONCEPT_NID_FOR_DESCRIPTION____SOLOR, PropertyEditorType.CONCEPT);
   propertySheetMenuItem.addPropertyToEdit("status", MetaData.STATUS_FOR_VERSION____SOLOR, PropertyEditorType.STATUS);
   propertySheetMenuItem.addPropertyToEdit("path", MetaData.PATH_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
   propertySheetMenuItem.addPropertyToEdit("module", MetaData.MODULE_NID_FOR_VERSION____SOLOR, PropertyEditorType.CONCEPT);
end

rule "Given a property set, populate the choice items"
   lock-on-active true
when
   $propertySheetMenuItem: PropertySheetMenuItem()
then
   for (Item item: $propertySheetMenuItem.getPropertySheetItems()) {
      insert(item);
   }
end

rule "if property specification is STATUS_FOR_VERSION____SOLOR then"

when
   $property: PropertySheetItemConceptWrapper(getSpecification() == MetaData.STATUS_FOR_VERSION____SOLOR)
then
   System.out.println("Add status capability");
end

rule "if property specification is DESCRIPTION_TYPE____SOLOR then "

when
   $property: PropertySheetItemConceptWrapper(getSpecification() == MetaData.DESCRIPTION_TYPE_FOR_DESCRIPTION____SOLOR)
then
   $property.getAllowedValues().add(MetaData.FULLY_QUALIFIED_NAME_DESCRIPTION_TYPE____SOLOR);
   $property.getAllowedValues().add(MetaData.REGULAR_NAME_DESCRIPTION_TYPE____SOLOR);
   $property.getAllowedValues().add(MetaData.DEFINITION_DESCRIPTION_TYPE____SOLOR);
   
end
rule "if property specification is CASE_SIGNIFICANCE_CONCEPT_NID_FOR_DESCRIPTION____SOLOR then "

when
   $property: PropertySheetItemConceptWrapper(getSpecification() == MetaData.CASE_SIGNIFICANCE_CONCEPT_NID_FOR_DESCRIPTION____SOLOR)
then
   $property.getAllowedValues().add(MetaData.DESCRIPTION_CASE_SENSITIVE____SOLOR);
   $property.getAllowedValues().add(MetaData.DESCRIPTION_NOT_CASE_SENSITIVE____SOLOR);
   $property.getAllowedValues().add(MetaData.DESCRIPTION_INITIAL_CHARACTER_CASE_SENSITIVE____SOLOR);
   
end
rule "if property specification is LANGUAGE_CONCEPT_NID_FOR_DESCRIPTION____SOLOR then "

when
   $property: PropertySheetItemConceptWrapper(getSpecification() == MetaData.LANGUAGE_CONCEPT_NID_FOR_DESCRIPTION____SOLOR)
then
   $property.getAllowedValues().add(MetaData.ENGLISH_LANGUAGE____SOLOR);
   $property.getAllowedValues().add(MetaData.SPANISH_LANGUAGE____SOLOR);
   $property.getAllowedValues().add(MetaData.FRENCH_LANGUAGE____SOLOR);
   $property.getAllowedValues().add(MetaData.DANISH_LANGUAGE____SOLOR);
   $property.getAllowedValues().add(MetaData.POLISH_LANGUAGE____SOLOR);
   $property.getAllowedValues().add(MetaData.DUTCH_LANGUAGE____SOLOR);
   $property.getAllowedValues().add(MetaData.LITHUANIAN_LANGUAGE____SOLOR);
   $property.getAllowedValues().add(MetaData.CHINESE_LANGUAGE____SOLOR);
   $property.getAllowedValues().add(MetaData.JAPANESE_LANGUAGE____SOLOR);
   $property.getAllowedValues().add(MetaData.SWEDISH_LANGUAGE____SOLOR);
   
end
